### ISSUE TITLE
Buggy in vue files

### ISSUE THREAD

**Issue by tecnoloco** [Rain-1214/vue-scss-variable-scan#2]
The usage in scss files is really good but in vue files is a little bit weird. When trying to find a variable defined inside src/assets/styles/_variables.scss it is not straight forward as it is in any scss file. Here it is an example of what is happening, I expect it is self explanatory.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15238607/46220823-f6a98d00-c310-11e8-91f3-fb0424a00674.gif)

**Comment by Rain-1214** [comment]
At first,I'm sorry for not replying for a long time, but I can't repeat you question on my Vscode.
If it is possible, can you provide the "_variables.scss" file that you used when you found the problem (if it is not convenient to disclose it, you can also send it to my email address: rainwh12138@gmail.com).
my Vscode version is 1.30.0 Typescript version is 3.2.2

**Comment by Rain-1214** [comment]
At first,I'm sorry for not replying for a long time, but I can't repeat you question on my Vscode.
If it is possible, can you provide the "_variables.scss" file that you used when you found the problem (if it is not convenient to disclose it, you can also send it to my email address: rainwh12138@gmail.com).
my Vscode version is 1.30.0 Typescript version is 3.2.2

**Comment by tecnoloco** [comment]
Here is the file.

```scss
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



    IMPORTANT!
    It is recommended to only include variables in this file,
    to prevent duplicated css in your final, compiled files.

    If you want to set the global styles for headings, lists,
    tables, etc. Use the root.scss file that is imported into the
    RootView Component



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
/////////////////////////////////////////
//                                LOGOS
/////////////////////////////////////////
$main-logo: "~assets/images/logo.png";
$main-logo-min: "~assets/images/logo-min.png";
$main-logo-negative: "~assets/images/logo-negative.png";
$main-logo--negative-min: "~assets/images/logo-negative-min.png";

/////////////////////////////////////////
//                                FONTS
/////////////////////////////////////////
$font-family-primary: "Montserrat", sans-serif;
$font-family-secondary: "Roboto", sans-serif;

/////////////////////////////////////////
//                           BREAKPOINTS
/////////////////////////////////////////
/**
  Used for the media query mixin
 */
$breakpoints: (
  "phone": 400px,
  "phone-wide": 480px,
  "phablet": 560px,
  "tablet-small": 640px,
  "tablet": 768px,
  "tablet-wide": 1024px,
  "desktop": 1248px,
  "macbook-pro": 1280px,
  "desktop-wide": 1440px
);

/////////////////////////////////////////
//                           MEDIAQUERIES
/////////////////////////////////////////
/**
  Used for the media query
 */
$desktop-HD: "(max-width: 1920px)";
$desktop: "(max-width: 1680px)";
$desktop-wide: "(max-width: 1440px)";
$MacBookPro: "(max-width: 1280px)";
$tablet-wide: "(max-width: 1024px)";

$input-color--active: $--color-primary;
$input-color--inactive: #dedede;
$input-color--hover: #a2a2a2;
$input-color--focus: #6c6c6c;
$input-color--error: $--color-danger;

$font-gray--primary: #5a5a5a;
$font-gray--secondary: #838383;

```
And here is my Vscode version.

Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by Rain-1214** [comment]
emmmm....I'm also can't repeat you question, I use the same input value as you,but my prompt is right.
![a](https://user-images.githubusercontent.com/23204067/50260988-742ef600-0445-11e9-811c-f5e9630591e3.gif)
I guess maybe same other extension impact my extension.can you provide you extension list of your Vscode.

**Comment by tecnoloco** [comment]
Hello again, here is my extension list:

Anjali.clipboard-history
christian-kohler.path-intellisense
dariofuzinato.vue-peek
dbaeumer.vscode-eslint
donjayamanne.githistory
Equinusocio.vsc-material-theme
geddski.macros
kortina.run-in-terminal
lihui.vs-color-picker
lunarlimbo.banner-comments-plus
MS-CEINTL.vscode-language-pack-es
msjsdiag.debugger-for-chrome
octref.vetur
Rain.vue-scss-variable-scan
sysoev.language-stylus
wayou.vscode-todo-highlight
xyz.local-history

**Comment by shanepadgett000** [comment]
I can concur that this is really buggy. I set the global path to the location of scss files, the indicator in vscode shows it has scanned and found 1 variable, which is correct, however intellisense only works on SOME css properties, instead of all of them. I should get variables for all CSS properties.

In the example below, the one variable I have defined in `$defaut-font-family`. The variable doesn't show for the `font-family` property, but it does show for the `color` property.

Works
![image](https://user-images.githubusercontent.com/41803694/51082703-3767bf00-16d2-11e9-8f8d-40ef66ae66e4.png)

Doesnt Work
![image](https://user-images.githubusercontent.com/41803694/51082706-42225400-16d2-11e9-8de8-e892c68bcf40.png)

**Comment by Rain-1214** [comment]
@shanepadgett your question is different from him.I only set a part of CSS properties to apply to smart tips because I think some property Vscode tips are smarter. but I provide the option of custom CSS property.
![_20190114151051](https://user-images.githubusercontent.com/23204067/51100127-8b2bf280-180f-11e9-8dc3-1f996290a6db.png)
I think I will add options likes 'ALL' in next version.
