### ISSUE TITLE
Duplicates list in .vue files

### ISSUE THREAD

**Issue by neonVoice** [Rain-1214/vue-scss-variable-scan#3]
Hello, i have a code structure like this:
![default](https://user-images.githubusercontent.com/21147332/52143841-97b4a580-266d-11e9-9852-71a3680181b9.png)
I set `vue-scss-variable-scan.globalPath` variable to **`/src/styles/**/*.scss`** 

When i tried to use variable in my `.vue file`, i got this:
![default](https://user-images.githubusercontent.com/21147332/52144097-596bb600-266e-11e9-885c-14965cd4e803.png)

I looked into `Controller\Main.ts` for function `scanScssVariable` and found that it just adds items to list.
```
if (key.startsWith('$')) {
  this.scssVariables.push(new ScssVariable(key, value.split(':')[1].trim()));
}
```

Maybe its better to check for duplicates, before addition ? I am not an expert in JS/TS, but seems like your extension is the only one that works for me. It would be great if you could implement that check or atleast give me code, that i need to insert into node_modules folder, so i wont see duplicates.

**Comment by Rain-1214** [comment]
At first,I'm sorry for not replying for a long time,i want to confirm one thing.Do you define duplicate variables? or you only define once but show a lot result?

**Comment by Rain-1214** [comment]
long time no result....
