### ISSUE TITLE
为什么不监听$输入

### ISSUE THREAD

**Issue by miaowwwww** [Rain-1214/vue-scss-variable-scan#9]
registerCompletionItemProvider里面监听的是 :  想问一下，为什么不监听$, 我自己尝试了一下。在scss文件中，是不生效的，其他的文件都行。
```
    vscode.languages.registerCompletionItemProvider(
      "scss",
      {

        provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.ProviderResult<vscode.CompletionItem[] | vscode.CompletionList> {
          console.log('document.lineAt(position).text===', document.lineAt(position).text);
          return [
            new vscode.CompletionItem("css-variable11122", vscode.CompletionItemKind.Text),
          ];
        },
      },
      "$"
    )
  );
```
想知道其中的原因，帮忙解解惑，谢谢大佬。

**Comment by Rain-1214** [comment]
github 改版之后我就看不太到最近的issue了，不太习惯。。。也不知道这么久了你还能看到么。。
第一个问题：
> registerCompletionItemProvider里面监听的是 : 想问一下，为什么不监听$

因为设计初衷还是为了写样式变量的。而vscode对css其实提示挺猛的。比如你打个bg敲了回车。vscode就能帮你输入好一整行：

> background: 光标 ;

所以而这个时候提示里就已经出现所有的变量了。冒号其实都不是你手动输入的。

而即使不考虑这个场景，冒号在语法上也是必须的，在输入冒号的时候提示里也出现了所有变量。而不必再输入一个字符才出现变量。

我觉得上述两个场景最常见而已。如果你有其它常用场景的话，也可以提出来看看需不需要改。

第二个问题：
你的 'css-variable11122' 里面没有 '$' 符号，所以理论上你就算按了 '$' 触发了事件，因为没有任何符合用户输入的提示。也就不会展示了。如果你给你的 CompletionItem 的 filterText 设置为 '$css-variable11122' 的话应该就可以正常看到提示了。

**Comment by Rain-1214** [comment]
有问题你再reopen吧。先关掉了。
